import Papa from 'papaparse';
import { TabularField } from '../types/schema';

export function exportWithPapaParseCSV(
  rows: Record<string, any>[],
  fields?: TabularField[],
  tableName: string = 'synthetic_dataset',
  seed?: number
): void {
  if (!rows || rows.length === 0) return;

  // Determine headers in order based on current schema configuration
  let headerKeys: string[];
  if (fields && fields.length > 0) {
    headerKeys = fields.map((f) => f.name);
    // Include any additional row keys if present (except internal _id)
    const rowKeys = Object.keys(rows[0]).filter((k) => k !== '_id');
    for (const key of rowKeys) {
      if (!headerKeys.includes(key)) {
        headerKeys.push(key);
      }
    }
  } else {
    headerKeys = Object.keys(rows[0]).filter((k) => k !== '_id');
  }

  // Format data rows cleanly for PapaParse
  const formattedData = rows.map((row) => {
    const item: Record<string, any> = {};
    for (const header of headerKeys) {
      const val = row[header];
      if (val === null || val === undefined) {
        item[header] = '';
      } else if (typeof val === 'object' && !(val instanceof Date)) {
        item[header] = JSON.stringify(val);
      } else {
        item[header] = val;
      }
    }
    return item;
  });

  const csvContent = Papa.unparse(
    {
      fields: headerKeys,
      data: formattedData,
    },
    {
      quotes: false,
      header: true,
      skipEmptyLines: false,
    }
  );

  const cleanTableName = (tableName || 'synthetic_dataset')
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '_');
  const filename = seed !== undefined
    ? `${cleanTableName}_seed${seed}.csv`
    : `${cleanTableName}_${Date.now()}.csv`;

  triggerDownload(csvContent, filename, 'text/csv;charset=utf-8;');
}

export function convertToCSV(rows: Record<string, any>[]): string {
  if (rows.length === 0) return '';

  const headers = Object.keys(rows[0]).filter((k) => k !== '_id');
  const csvLines: string[] = [];

  // Header line
  csvLines.push(headers.map(escapeCSVValue).join(','));

  // Data lines
  for (const row of rows) {
    const values = headers.map((header) => {
      const val = row[header];
      if (val === null || val === undefined) return '';
      return escapeCSVValue(String(val));
    });
    csvLines.push(values.join(','));
  }

  return csvLines.join('\n');
}

function escapeCSVValue(val: string): string {
  if (val.includes(',') || val.includes('"') || val.includes('\n') || val.includes('\r')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

export function convertToJSON(rows: Record<string, any>[]): string {
  // Strip internal _id field before export
  const cleanRows = rows.map((r) => {
    const copy = { ...r };
    delete copy._id;
    return copy;
  });
  return JSON.stringify(cleanRows, null, 2);
}

export function convertToSQL(tableName: string, rows: Record<string, any>[]): string {
  if (rows.length === 0) return '';
  const headers = Object.keys(rows[0]).filter((k) => k !== '_id');

  const statements: string[] = [
    `-- Generated by Synthora Synthetic Studio`,
    `-- Table: ${tableName} (${rows.length} rows)`,
    '',
  ];

  for (const row of rows) {
    const colList = headers.map((h) => `\`${h}\``).join(', ');
    const valList = headers
      .map((h) => {
        const val = row[h];
        if (val === null || val === undefined) return 'NULL';
        if (typeof val === 'number') return `${val}`;
        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
        return `'${String(val).replace(/'/g, "''")}'`;
      })
      .join(', ');

    statements.push(`INSERT INTO \`${tableName}\` (${colList}) VALUES (${valList});`);
  }

  return statements.join('\n');
}

export interface SchemaConfigFile {
  version: '1.0';
  generator: 'Synthora Synthetic Studio';
  exportedAt: string;
  schema: {
    name: string;
    seed: number;
    recordCount: number;
    fields: any[];
  };
}

export function exportSchemaConfigurationJSON(config: {
  name?: string;
  seed: number;
  recordCount: number;
  fields: any[];
}): string {
  const schemaFile: SchemaConfigFile = {
    version: '1.0',
    generator: 'Synthora Synthetic Studio',
    exportedAt: new Date().toISOString(),
    schema: {
      name: config.name || 'custom_synthetic_schema',
      seed: config.seed,
      recordCount: config.recordCount,
      fields: config.fields,
    },
  };
  return JSON.stringify(schemaFile, null, 2);
}

export function parseSchemaJSON(rawJson: string): {
  success: boolean;
  data?: {
    name: string;
    seed: number;
    recordCount: number;
    fields: any[];
  };
  error?: string;
} {
  try {
    const parsed = JSON.parse(rawJson);
    if (parsed.schema && Array.isArray(parsed.schema.fields)) {
      return {
        success: true,
        data: {
          name: parsed.schema.name || 'imported_schema',
          seed: typeof parsed.schema.seed === 'number' ? parsed.schema.seed : 42,
          recordCount: typeof parsed.schema.recordCount === 'number' ? parsed.schema.recordCount : 50,
          fields: parsed.schema.fields,
        },
      };
    } else if (Array.isArray(parsed.fields)) {
      return {
        success: true,
        data: {
          name: parsed.name || 'imported_schema',
          seed: typeof parsed.seed === 'number' ? parsed.seed : 42,
          recordCount: typeof parsed.recordCount === 'number' ? parsed.recordCount : 50,
          fields: parsed.fields,
        },
      };
    } else if (Array.isArray(parsed)) {
      // Direct array of fields
      return {
        success: true,
        data: {
          name: 'imported_schema',
          seed: 42,
          recordCount: 50,
          fields: parsed,
        },
      };
    }
    return { success: false, error: 'Invalid schema JSON format. Expected fields array.' };
  } catch (err: any) {
    return { success: false, error: err.message || 'Failed to parse JSON file' };
  }
}

export function triggerDownload(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

