import { ProblemPreset, TabularField } from '../types/schema';

export const PROBLEM_PRESETS: ProblemPreset[] = [
  {
    id: 'privacy',
    title: 'Privacy & Compliance',
    subtitle: 'GDPR, HIPAA & CCPA Sanitization',
    painDescription: 'Production data cannot be moved to dev/staging without violating compliance mandates or risking PII leaks.',
    tagline: 'Zero-PII synthetic customer & healthcare records with realistic statistical structure.',
    targetDomain: 'tabular',
    recommendedSeed: 404,
    recommendedCount: 50,
    badge: 'GDPR / HIPAA Safe',
    samplePrompt: 'Create 50 anonymized clinical patient records with synthetic MRN, email, country, diagnosis status, and encounter dates.',
    stats: [
      { label: 'PII Leakage Risk', value: '0.0%' },
      { label: 'Network Requests', value: '0 (Offline)' },
      { label: 'De-identification', value: '100% Synthetic' },
    ],
    fields: [
      { id: 'f1', name: 'patient_id', type: 'uuid', nullRate: 0, outlierRate: 0 },
      { id: 'f2', name: 'full_name', type: 'full_name', nullRate: 0, outlierRate: 0 },
      { id: 'f3', name: 'anonymized_email', type: 'email', nullRate: 0, outlierRate: 0 },
      { id: 'f4', name: 'admission_date', type: 'date', nullRate: 0, outlierRate: 0 },
      { id: 'f5', name: 'treatment_cost_cents', type: 'integer_cents', min: 25000, max: 750000, nullRate: 0, outlierRate: 0 },
      { id: 'f6', name: 'clinical_status', type: 'status', nullRate: 2, outlierRate: 0 },
      { id: 'f7', name: 'facility_country', type: 'country', nullRate: 0, outlierRate: 0 },
      { id: 'f8', name: 'emergency_phone', type: 'phone', nullRate: 5, outlierRate: 0 },
    ],
  },
  {
    id: 'scarce_data',
    title: 'Scarce or Messy Data',
    subtitle: 'Null Rate & Missing Values Simulator',
    painDescription: 'Real production datasets have missing columns, sparse distributions, and imperfect data feeds that crash naive code.',
    tagline: 'Configurable null injection and realistic dirty data distributions.',
    targetDomain: 'tabular',
    recommendedSeed: 777,
    recommendedCount: 75,
    badge: 'Dirty Data Stress',
    samplePrompt: 'Generate 75 customer records with realistic 15% null rates on contact numbers, job titles, and company names.',
    stats: [
      { label: 'Null Injection Rate', value: '15.0%' },
      { label: 'Field Sparsity', value: 'Variable' },
      { label: 'Data Cleanliness', value: 'Realistic Noise' },
    ],
    fields: [
      { id: 's1', name: 'record_id', type: 'uuid', nullRate: 0, outlierRate: 0 },
      { id: 's2', name: 'customer_name', type: 'full_name', nullRate: 2, outlierRate: 0 },
      { id: 's3', name: 'primary_email', type: 'email', nullRate: 8, outlierRate: 0 },
      { id: 's4', name: 'direct_phone', type: 'phone', nullRate: 20, outlierRate: 0 },
      { id: 's5', name: 'company_employer', type: 'company', nullRate: 15, outlierRate: 0 },
      { id: 's6', name: 'job_title', type: 'job_title', nullRate: 18, outlierRate: 0 },
      { id: 's7', name: 'annual_spend_cents', type: 'integer_cents', min: 10000, max: 250000, nullRate: 10, outlierRate: 0 },
      { id: 's8', name: 'account_state', type: 'status', nullRate: 5, outlierRate: 0 },
    ],
  },
  {
    id: 'slow_access',
    title: 'Slow Data Access',
    subtitle: 'Instant Staging Fixtures',
    painDescription: 'Waiting weeks for DBA approval or data warehouse permissions stalls sprint development and QA pipelines.',
    tagline: 'Generate rich staging tables in under 15 milliseconds without approval queues.',
    targetDomain: 'tabular',
    recommendedSeed: 1234,
    recommendedCount: 100,
    badge: 'Instant Access',
    samplePrompt: 'Provide 100 enterprise users with names, corporate emails, cities, IP addresses, and creation timestamps.',
    stats: [
      { label: 'Wait Time', value: '< 15 ms' },
      { label: 'DBA Tickets', value: '0 Required' },
      { label: 'Export Options', value: 'CSV / JSON / SQL' },
    ],
    fields: [
      { id: 'sa1', name: 'user_id', type: 'uuid', nullRate: 0, outlierRate: 0 },
      { id: 'sa2', name: 'user_name', type: 'full_name', nullRate: 0, outlierRate: 0 },
      { id: 'sa3', name: 'corp_email', type: 'email', nullRate: 0, outlierRate: 0 },
      { id: 'sa4', name: 'ip_address', type: 'ip_address', nullRate: 0, outlierRate: 0 },
      { id: 'sa5', name: 'assigned_city', type: 'city', nullRate: 0, outlierRate: 0 },
      { id: 'sa6', name: 'billing_address', type: 'address', nullRate: 0, outlierRate: 0 },
      { id: 'sa7', name: 'created_at', type: 'timestamp', nullRate: 0, outlierRate: 0 },
    ],
  },
  {
    id: 'edge_cases',
    title: 'Missed Edge Cases',
    subtitle: 'Extreme Outliers & Boundary Tests',
    painDescription: 'Systems fail in production on negative amounts, boundary dates, overflow strings, and malformed inputs.',
    tagline: 'Intentionally inject boundary outliers and stress test input validation routines.',
    targetDomain: 'tabular',
    recommendedSeed: 999,
    recommendedCount: 40,
    badge: 'Boundary Testing',
    samplePrompt: 'Stress-test pricing engine with 40 rows containing boundary dates, negative balances, and non-ASCII test vectors.',
    stats: [
      { label: 'Outlier Injection', value: '12.5%' },
      { label: 'Boundary Vectors', value: 'Negative/Leap' },
      { label: 'Crash Protection', value: 'Pre-flight' },
    ],
    fields: [
      { id: 'e1', name: 'identifier', type: 'string', prefix: 'BOUNDARY', nullRate: 0, outlierRate: 15 },
      { id: 'e2', name: 'contact_name', type: 'full_name', nullRate: 0, outlierRate: 12 },
      { id: 'e3', name: 'account_balance_cents', type: 'integer_cents', min: 1000, max: 100000, nullRate: 0, outlierRate: 20 },
      { id: 'e4', name: 'effective_date', type: 'date', nullRate: 0, outlierRate: 15 },
      { id: 'e5', name: 'risk_score', type: 'float', min: 0.1, max: 99.9, nullRate: 0, outlierRate: 15 },
      { id: 'e6', name: 'contact_email', type: 'email', nullRate: 0, outlierRate: 10 },
    ],
  },
  {
    id: 'relational',
    title: 'Linked Demo Data',
    subtitle: 'PK / FK Referential Integrity',
    painDescription: 'Single mock tables cannot demo complex workflows: child orders orphan without matching parent customers.',
    tagline: 'Three-tier relational schema (Customers → Orders → Order Items) with guaranteed referential integrity.',
    targetDomain: 'relational',
    recommendedSeed: 42,
    recommendedCount: 20,
    badge: '100% FK Verified',
    samplePrompt: 'Build a relational e-commerce store with 20 customers, linked order histories, and verified line item subtotals.',
    stats: [
      { label: 'Referential Integrity', value: '100.0%' },
      { label: 'Orphaned Records', value: '0' },
      { label: 'Hierarchy Depth', value: '3 Tables' },
    ],
  },
  {
    id: 'documents',
    title: 'Document Testing',
    subtitle: 'Reconciled Financial Documents',
    painDescription: 'Testing PDF parsers, invoice intake workflows, and bank reconciliation algorithms requires exact arithmetic.',
    tagline: 'Invoices with exact line item sums and bank statements with mathematically verified running balances.',
    targetDomain: 'documents',
    recommendedSeed: 888,
    recommendedCount: 1,
    badge: 'Exact Math Reconciled',
    samplePrompt: 'Generate reconciled enterprise invoices with Net 30 terms, tax rates, line items, and bank ledger statements.',
    stats: [
      { label: 'Rounding Error', value: '$0.00 (Exact)' },
      { label: 'Balance Reconciliation', value: '100% Parity' },
      { label: 'Formats', value: 'Live Paper / PDF' },
    ],
  },
];

export const DEFAULT_TABULAR_FIELDS: TabularField[] = [
  { id: 'col_1', name: 'customer_id', type: 'uuid', nullRate: 0, outlierRate: 0 },
  { id: 'col_2', name: 'full_name', type: 'full_name', nullRate: 0, outlierRate: 0 },
  { id: 'col_3', name: 'email', type: 'email', nullRate: 0, outlierRate: 0 },
  { id: 'col_4', name: 'annual_revenue_cents', type: 'integer_cents', min: 50000, max: 950000, nullRate: 0, outlierRate: 0 },
  { id: 'col_5', name: 'country', type: 'country', nullRate: 0, outlierRate: 0 },
  { id: 'col_6', name: 'account_status', type: 'status', nullRate: 0, outlierRate: 0 },
  { id: 'col_7', name: 'onboarding_date', type: 'date', nullRate: 0, outlierRate: 0 },
];
